tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "git"
brew "tree"
brew "yarn", args: ["without-node"]
cask "1password"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "dash"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "maczip4win"
cask "skype"
cask "visual-studio-code"
